package com.saturnkuji.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import org.json.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    KujiView view;
    @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(Color.rgb(5,6,10)); view=new KujiView(this); setContentView(view);}
}

class KujiView extends View {
    Paint p=new Paint(3); Paint stroke=new Paint(3); Random rnd=new Random(); android.content.SharedPreferences sp;
    int W,H; int mode=0; // 0 random 1 paper 2 chest 3 roulette 4 save 5 admin
    boolean popup=false; String popupType=""; String winner="홍길동"; ArrayList<Product> all=new ArrayList<>(), remaining=new ArrayList<>(); ArrayList<History> history=new ArrayList<>(); ArrayList<Product> lastDraw=new ArrayList<>();
    ArrayList<Product> paperSlots=new ArrayList<>(), chestSlots=new ArrayList<>(); boolean rouletteRunning=false; long rouletteStart=0; Product result=null;
    int total=100; int[] rankTotal={5,15,20,25,35}; int[] rankDraw={0,0,0,0,0}; String[] ranks={"S","A","B","C","D"}; int[] rankColors={0xFFFFD54A,0xFFFFC107,0xFFE53935,0xFF42A5F5,0xFFF2F2F2};
    SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.KOREA);
    KujiView(Context c){super(c); p.setTypeface(Typeface.create("sans",Typeface.BOLD)); stroke.setStyle(Paint.Style.STROKE); stroke.setStrokeWidth(2); sp=c.getSharedPreferences("saturn",0); load(); }
    static class Product {int id;String rank,name; Product(int i,String r,String n){id=i;rank=r;name=n;} }
    static class History {int id;String rank,name,winner,time; History(int i,String r,String n,String w,String t){id=i;rank=r;name=n;winner=w;time=t;} }
    int rc(String r){return rankColors[Math.max(0,Arrays.asList(ranks).indexOf(r))];}
    protected void onSizeChanged(int w,int h,int ow,int oh){W=w;H=h; buildSlots();}
    void load(){
      total=sp.getInt("total",100); for(int i=0;i<5;i++){rankTotal[i]=sp.getInt("rt"+i,new int[]{5,15,20,25,35}[i]);rankDraw[i]=0;}
      winner=sp.getString("winner","홍길동"); all.clear(); remaining.clear();
      for(int i=1;i<=total;i++){String r=ranks[rankFor(i)]; Product x=new Product(i,r,"상품 "+String.format(Locale.KOREA,"%03d",i));all.add(x);}
      try{JSONArray used=new JSONArray(sp.getString("used","[]")); HashSet<Integer> u=new HashSet<>();for(int i=0;i<used.length();i++)u.add(used.getInt(i));for(Product x:all)if(!u.contains(x.id))remaining.add(x); JSONArray hs=new JSONArray(sp.getString("history","[]"));for(int i=0;i<hs.length();i++){JSONObject o=hs.getJSONObject(i);history.add(new History(o.getInt("id"),o.getString("rank"),o.getString("name"),o.getString("winner"),o.getString("time")));}}
      catch(Exception e){remaining.addAll(all);}
      for(History h:history)rankDraw[Math.max(0,Arrays.asList(ranks).indexOf(h.rank))]++;
    }
    int rankFor(int id){int c=0;for(int i=0;i<5;i++){c+=rankTotal[i];if(id<=c)return i;}return 4;}
    void save(){try{JSONArray u=new JSONArray();for(Product x:all)if(!contains(remaining,x.id))u.put(x.id);sp.edit().putInt("total",total).putString("winner",winner).putString("used",u.toString()).putString("history",histJson()).apply();for(int i=0;i<5;i++)sp.edit().putInt("rt"+i,rankTotal[i]).apply();}catch(Exception ignored){}}
    String histJson(){JSONArray a=new JSONArray();try{for(History h:history){JSONObject o=new JSONObject();o.put("id",h.id);o.put("rank",h.rank);o.put("name",h.name);o.put("winner",h.winner);o.put("time",h.time);a.put(o);}}catch(Exception ignored){}return a.toString();}
    boolean contains(ArrayList<Product> a,int id){for(Product x:a)if(x.id==id)return true;return false;}
    Product take(){if(remaining.isEmpty())return null;Product x=remaining.remove(rnd.nextInt(remaining.size())); addHistory(x); return x;}
    void addHistory(Product x){String t=df.format(new Date());history.add(new History(x.id,x.rank,x.name,winner,t));lastDraw.add(x);rankDraw[Math.max(0,Arrays.asList(ranks).indexOf(x.rank))]++;result=x;save();}
    void undo(){if(history.isEmpty())return;History h=history.remove(history.size()-1);Product x=find(h.id);if(x!=null&&!contains(remaining,x.id))remaining.add(x);rankDraw[Math.max(0,Arrays.asList(ranks).indexOf(h.rank))]--;result=null;save();invalidate();}
    Product find(int id){for(Product x:all)if(x.id==id)return x;return null;}
    void resetSlots(){Collections.shuffle(remaining,rnd);buildSlots();invalidate();}
    void buildSlots(){paperSlots.clear();paperSlots.addAll(remaining);Collections.shuffle(paperSlots,rnd);chestSlots.clear();chestSlots.addAll(remaining);Collections.shuffle(chestSlots,rnd);}
    void drawText(Canvas c,String s,float x,float y,float size,int color,Paint.Align align){p.setTextSize(size);p.setColor(color);p.setTextAlign(align);p.setStyle(Paint.Style.FILL);c.drawText(s,x,y,p);}
    void box(Canvas c,float l,float t,float r,float b,int fill,int border,float rad){p.setColor(fill);p.setStyle(Paint.Style.FILL);c.drawRoundRect(l,t,r,b,rad,rad,p);stroke.setColor(border);c.drawRoundRect(l,t,r,b,rad,rad,stroke);}
    protected void onDraw(Canvas c){super.onDraw(c); drawBg(c); drawHeader(c); drawContent(c); drawBottom(c); if(popup)drawPopup(c);}
    void drawBg(Canvas c){int col= mode==1?0xFF15102A:mode==2?0xFF102018:mode==3?0xFF23102C:0xFF07111E; c.drawColor(col);p.setColor(0x1600BFFF);for(int i=0;i<30;i++){float x=(i*83)%Math.max(1,W),y=80+(i*47)%Math.max(1,H-180);c.drawCircle(x,y,2+(i%4),p);} }
    void drawHeader(Canvas c){box(c,10,8,W-10,68,0xDD0A0D16,0xFFB88A24,16);drawText(c,"☠ SATURNKUJI",20,43,22,0xFFFFD54A,Paint.Align.LEFT);drawText(c,winner+" 님",W*0.43f,42,16,Color.WHITE,Paint.Align.CENTER);drawText(c,"◉ 12,450",W-135,42,16,0xFFFFD54A,Paint.Align.CENTER);String[] top={"↩","↻","⚙","🎁","📊","🏆"};for(int i=0;i<6;i++){float x=W-390+i*62;box(c,x,14,x+52,60,0xFF111624,0xFF9D7A24,10);drawText(c,top[i],x+26,46,22,Color.WHITE,Paint.Align.CENTER);} }
    void drawContent(Canvas c){String title=mode==0?"랜덤뽑기 · 해적 모험풍":mode==1?"종이뽑기 · 한국식 번호판":mode==2?"상자뽑기 · 사다리 + 해적 보물상자":mode==3?"룰렛뽑기 · 드래곤볼풍":mode==4?"저장 · 당첨 상품": "관리자모드";drawText(c,title,W/2f,98,22,0xFFFFD54A,Paint.Align.CENTER);
      if(mode==0)drawRandom(c);else if(mode==1)drawPaper(c);else if(mode==2)drawChest(c);else if(mode==3)drawRoulette(c);else if(mode==4)drawSave(c);else drawAdmin(c);
    }
    void drawRandom(Canvas c){drawText(c,"해적선 · 바다 · 모험가 캐릭터",W/2f,128,14,0xFFB5C8D8,Paint.Align.CENTER);float cx=W/2f,cy=250; p.setColor(0xFF121B2A);c.drawCircle(cx,cy,118,p);stroke.setColor(0xFFFFC93D);stroke.setStrokeWidth(5);c.drawCircle(cx,cy,118,stroke);for(int i=0;i<18;i++){float a=i*0.35f;float x=cx+(float)Math.cos(a)*((i%3)*28+28),y=cy+(float)Math.sin(a)*((i%3)*28+28);p.setColor(rankColors[i%5]);c.drawCircle(x,y,14,p);}drawText(c,"🎱",cx,cy+15,50,Color.WHITE,Paint.Align.CENTER);String[] b={"1회 뽑기","3회 뽑기","5회 뽑기","10회 뽑기"};for(int i=0;i<4;i++){box(c,18,160+i*48,125,201+i*48,0xCC101B2D,0xFFB88A24,10);drawText(c,b[i],71,187+i*48,15,Color.WHITE,Paint.Align.CENTER);}drawResultStrip(c,390);}
    void drawPaper(Canvas c){drawText(c,"달빛 · 안개 · 검객 모험가",W/2f,128,14,0xFFD6C9FF,Paint.Align.CENTER);int cols=5, start=150, gap=6, cell=(W-40-gap*(cols-1))/cols;for(int i=0;i<Math.min(total,50);i++){int row=i/cols,col=i%cols;float l=20+col*(cell+gap),t=start+row*(42+gap);box(c,l,t,l+cell,t+42,0xFFE8DCC5,0xFF6C5130,5);drawText(c,String.valueOf(i+1),l+cell/2,t+28,16,0xFF20160F,Paint.Align.CENTER);}drawText(c,"번호를 선택하면 종이가 벗겨지며 등급 이펙트가 공개됩니다",W/2f,390,13,0xFFFFFFFF,Paint.Align.CENTER);drawResultStrip(c,420);}
    void drawChest(Canvas c){drawText(c,"사다리형 추첨 · 해적 보물창고",W/2f,128,14,0xFFBCE8D0,Paint.Align.CENTER);int n=Math.min(10,Math.max(5,remaining.size()));float left=45,right=W-45, step=(right-left)/(n-1);for(int i=0;i<n;i++){float x=left+i*step;stroke.setColor(0xFFD7A52A);stroke.setStrokeWidth(2);c.drawLine(x,155,x,340,stroke);box(c,x-28,330,x+28,380,0xFF5A3519,0xFFD7A52A,8);drawText(c,"▣",x,363,25,0xFFFFC94A,Paint.Align.CENTER);if(i<n-1&&i%2==0)c.drawLine(x,220,x+step,260,stroke);}drawText(c,"👤",left,150,28,Color.WHITE,Paint.Align.CENTER);drawText(c,"시작 위치를 선택하세요",W/2f,405,16,Color.WHITE,Paint.Align.CENTER);drawResultStrip(c,440);}
    void drawRoulette(Canvas c){float cx=W/2f,cy=260,r=Math.min(W,H)*0.31f;stroke.setStrokeWidth(5);stroke.setColor(0xFFFFC52E);c.drawCircle(cx,cy,r,stroke);int n=8;for(int i=0;i<n;i++){float a=(float)(i*2*Math.PI/n)-1.57f;Path path=new Path();path.moveTo(cx,cy);path.lineTo(cx+(float)Math.cos(a)*r,cy+(float)Math.sin(a)*r);path.lineTo(cx+(float)Math.cos(a+2*Math.PI/n)*r,cy+(float)Math.sin(a+2*Math.PI/n)*r);path.close();p.setColor(new int[]{0xFFE53935,0xFF1E88E5,0xFFFFC107,0xFF8E24AA}[i%4]);c.drawPath(path,p);drawText(c,new String[]{"홍길동","김철수","이영희","박민수","최지우","정다은","한서연","강민호"}[i],cx+(float)Math.cos(a+Math.PI/n)*r*.58f,cy+(float)Math.sin(a+Math.PI/n)*r*.58f,13,Color.WHITE,Paint.Align.CENTER);}drawText(c,"▼",cx,cy-r+12,28,Color.WHITE,Paint.Align.CENTER);box(c,cx-100,cy+r+25,cx+100,cy+r+80,0xFFDB6D12,0xFFFFD54A,16);drawText(c,rouletteRunning?"룰렛 회전중…":"룰렛 시작",cx,cy+r+61,20,Color.WHITE,Paint.Align.CENTER);if(result!=null){drawText(c,result.name,W/2f,cy+r+115,24,0xFFFFD54A,Paint.Align.CENTER);}}
    void drawResultStrip(Canvas c,int y){if(result==null)return;box(c,18,y,W-18,y+105,0xCC0A0D16,0xFFB88A24,14);drawText(c,"뽑기 결과",35,y+25,15,0xFFFFD54A,Paint.Align.LEFT);drawText(c,result.rank+" · "+result.name,W/2f,y+55,22,rc(result.rank),Paint.Align.CENTER);drawText(c,String.format(Locale.KOREA,"%03d",result.id)+" · "+winner,W/2f,y+82,15,Color.WHITE,Paint.Align.CENTER);}
    void drawSave(Canvas c){int y=135;for(int i=Math.max(0,history.size()-7);i<history.size();i++){History h=history.get(i);box(c,18,y,W-18,y+48,0xCC0A0D16,0xFF4B3A1D,10);drawText(c,String.format(Locale.KOREA,"%03d",h.id),32,y+31,15,Color.WHITE,Paint.Align.LEFT);drawText(c,h.rank,W*.18f,y+31,18,rc(h.rank),Paint.Align.CENTER);drawText(c,h.name,W*.42f,y+31,15,Color.WHITE,Paint.Align.CENTER);drawText(c,h.winner,W*.63f,y+31,14,0xFFE8D8B0,Paint.Align.CENTER);drawText(c,h.time.substring(0,16),W-25,y+31,12,0xFFBFC8D1,Paint.Align.RIGHT);y+=56;}drawText(c,"당첨시간 · 당첨상품 · 당첨날짜",W/2f,H-125,14,0xFFB88A24,Paint.Align.CENTER);}
    void drawAdmin(Canvas c){drawText(c,"상품등록 / 등급·수량 / 이미지 / 배치 / 백업",W/2f,135,15,0xFFE8D8B0,Paint.Align.CENTER);String[] a={"상품등록","등급/수량 설정","상품 이미지 관리","번호/상품 섞기","전체 리셋","데이터 백업"};for(int i=0;i<a.length;i++){int col=i%2,row=i/2;float l=25+col*(W-55)/2f,t=165+row*65;box(c,l,t,l+(W-70)/2f,t+52,0xCC111624,0xFF8F6A22,12);drawText(c,a[i],l+(W-70)/4f,t+32,15,Color.WHITE,Paint.Align.CENTER);}drawText(c,"총 상품 "+total+"개 · 뽑힌 "+(total-remaining.size())+"개 · 남은 "+remaining.size()+"개",W/2f,390,18,0xFFFFD54A,Paint.Align.CENTER);}
    void drawBottom(Canvas c){String[] names={"랜덤뽑기","종이뽑기","상자뽑기","룰렛뽑기","저장","관리자모드"};int n=6;float bw=(W-18-(n-1)*4)/n;for(int i=0;i<n;i++){float l=9+i*(bw+4);int fill=i==mode?0xFF6B3D0A:0xCC111724;box(c,l,H-72,l+bw,H-12,fill,rc(i==0?"S":i==1?"A":i==2?"B":i==3?"C":"D"),12);drawText(c,names[i],l+bw/2,H-37,12,Color.WHITE,Paint.Align.CENTER);}}
    void drawPopup(Canvas c){p.setColor(0xAA000000);c.drawRect(0,0,W,H,p);float l=18,t=90,r=W-18,b=H-95;box(c,l,t,r,b,0xFF0C101A,0xFFD7A52A,18);String title=popupType.equals("status")?"📊 상품 현황":popupType.equals("history")?"🏆 당첨자 현황":popupType.equals("register")?"🎁 상품등록":popupType.equals("settings")?"⚙ 상품설정":"↩ 최근 당첨 취소";drawText(c,title,W/2f,t+38,21,0xFFFFD54A,Paint.Align.CENTER);if(popupType.equals("status")){drawText(c,"총 상품  "+total+"개",45,t+80,17,Color.WHITE,Paint.Align.LEFT);drawText(c,"뽑힌 상품  "+(total-remaining.size())+"개",45,t+110,17,Color.WHITE,Paint.Align.LEFT);drawText(c,"남은 상품  "+remaining.size()+"개",45,t+140,17,Color.WHITE,Paint.Align.LEFT);for(int i=0;i<5;i++)drawText(c,ranks[i]+"급  총 "+rankTotal[i]+" / 뽑힘 "+rankDraw[i]+" / 남음 "+(rankTotal[i]-rankDraw[i]),45,t+180+i*34,15,rankColors[i],Paint.Align.LEFT);}else if(popupType.equals("history")){int y=(int)t+80;for(int i=Math.max(0,history.size()-8);i<history.size();i++){History h=history.get(i);drawText(c,String.format(Locale.KOREA,"%03d  %s  %s  %s  %s",h.id,h.rank,h.name,h.winner,h.time),35,y,12,Color.WHITE,Paint.Align.LEFT);y+=30;}}else if(popupType.equals("register")){drawText(c,"총 상품 개수: "+total+"개",45,t+90,18,Color.WHITE,Paint.Align.LEFT);drawText(c,"S/A/B/C/D 등급 수량은 총 상품 수에 맞춰 저장",45,t+125,13,0xFFD7DDE5,Paint.Align.LEFT);for(int i=0;i<5;i++)drawText(c,ranks[i]+"급  "+rankTotal[i]+"개",60,t+170+i*35,17,rankColors[i],Paint.Align.LEFT);drawText(c,"예: 총 39개로 저장하면 종이번호도 1~39 자동 생성",45,b-80,13,0xFFFFD54A,Paint.Align.LEFT);}else if(popupType.equals("settings")){drawText(c,"상품 설정은 관리자모드와 공통 DB로 연동됩니다.",45,t+90,15,Color.WHITE,Paint.Align.LEFT);drawText(c,"상품명 · 이미지 · 등급 · 수량 · 사용여부",45,t+125,15,0xFFD7DDE5,Paint.Align.LEFT);}else{drawText(c,"최근 당첨 1개를 되돌립니다.",W/2f,t+100,17,Color.WHITE,Paint.Align.CENTER);drawText(c,"저장 상품 / 당첨자 기록 / 수량까지 복구",W/2f,t+135,14,0xFFFFC7C7,Paint.Align.CENTER);}box(c,W/2-70,b-55,W/2+70,b-15,0xFF172234,0xFFD7A52A,10);drawText(c,"닫기",W/2f,b-29,15,Color.WHITE,Paint.Align.CENTER);}
    public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX(),y=e.getY();
      if(popup){if(y>H-160){popup=false;invalidate();return true;}return true;}
      if(y>H-90){int n=6;float bw=(W-18-(n-1)*4)/n;int idx=(int)((x-9)/(bw+4));if(idx>=0&&idx<6){mode=idx;result=null;invalidate();}return true;}
      if(y<75&&x>W-400){int idx=(int)((x-(W-390))/62);if(idx==0){undo();}else if(idx==1){resetSlots();}else if(idx==2){popup=true;popupType="settings";}else if(idx==3){popup=true;popupType="register";}else if(idx==4){popup=true;popupType="status";}else if(idx==5){popup=true;popupType="history";}return true;}
      if(mode==0&&y>150&&y<360){int k=(int)((y-160)/48);int count=new int[]{1,3,5,10}[Math.max(0,Math.min(3,k))];lastDraw.clear();for(int i=0;i<count;i++)take();invalidate();return true;}
      if(mode==1&&y>145&&y<390){int cols=5,gap=6,cell=(W-40-gap*4)/5;int col=(int)((x-20)/(cell+gap)),row=(int)((y-150)/(48));int num=row*5+col+1;if(num>=1&&num<=total){Product q=find(num);if(q!=null&&contains(remaining,q.id)){remaining.remove(q);addHistory(q);invalidate();}}return true;}
      if(mode==2&&y>320&&y<410){int n=Math.min(10,Math.max(5,remaining.size()));float left=45,right=W-45,step=(right-left)/(n-1);int idx=Math.max(0,Math.min(n-1,Math.round((x-left)/step)));if(idx<chestSlots.size()){Product q=chestSlots.get(idx);if(contains(remaining,q.id)){remaining.remove(q);addHistory(q);}}invalidate();return true;}
      if(mode==3&&y>500){rouletteRunning=true;rouletteStart=System.currentTimeMillis();postDelayed(()->{Product q=take();rouletteRunning=false;invalidate();},1600);invalidate();return true;}
      return true;
    }
}
